default: &default
  GOOGLE_CLIENT_ID: 831320260608-p4593a46j8tjsbesp2o1dc46ev13mbd8.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: l6m2sVrQ_7K3IVsg7ax39dJW
  GOOGLE_CLIENT_CODE: 4/2oab4jE5AVGeRD6h4y3skCwpIX9Y--2nbtiWYpzxf1o
  AUTH_REDIRECT_URL: http://localhost:3000/authorization_code

development:
  <<: *default

test:
  <<: *default
  GOOGLE_CLIENT_CODE: 4/O6FjufxVN73Cb2UF4STkSc6MO6WnyIDYE2z-CcAt-cQ
  ACCESS_TOKEN: ya29.3QFCID0adfMDK5egRJuUPo-a5b10tU8GhCnc0UGL-yPrGLqdziqM-PdKYdG_OAS6JW-O
  AUTH_REDIRECT_URL: urn:ietf:wg:oauth:2.0:oob

production:
  GOOGLE_CLIENT_ID: 831320260608-82epjq6mlhle3km9isd5ssmvruq5knjr.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: igE7CaWeDseXU8KHJNLan4W9
  AUTH_REDIRECT_URL: http://google-images.herokuapp.com/authorization_code
